import type { TrainingModule } from '@/lib/admin/training/types'

/** Step-by-step training modules for staff handover (static content — no runtime side effects). */
export const TRAINING_MODULES: readonly TrainingModule[] = [
  {
    slug: 'login-dashboard-overview',
    title: 'Login & dashboard overview',
    description: 'Sign in, understand the command center, and navigate the admin shell safely.',
    track: 'operations',
    roles: 'all',
    keywords: ['login', 'dashboard', 'command center', 'navigation', 'sidebar'],
    estimatedMinutes: 15,
    objectives: [
      'Sign in with your staff account and land on the command center',
      'Read live metrics without changing operational data',
      'Use the sidebar and ops alert bell',
    ],
    steps: [
      {
        id: 's1',
        title: 'Staff login',
        body: 'Open the admin URL and sign in with your assigned email. Your role (support, fleet, finance, KYC, ops) is set in user metadata — never share credentials.',
        tip: 'If you see Access restricted, your role lacks permission for that page. Ask ops admin.',
      },
      {
        id: 's2',
        title: 'Command center at a glance',
        body: 'The home dashboard (/admin) shows booking pipeline counts, finance snapshot, fleet utilization, KYC queue depth, and derived alerts. Use it for morning stand-up, not for edits.',
        adminHref: '/admin',
      },
      {
        id: 's3',
        title: 'Sidebar navigation',
        body: 'Menu items are permission-filtered. You only see modules your role can access: Bookings, Fleet, KYC, Payments, etc. Collapse the sidebar on smaller screens via the toggle.',
      },
      {
        id: 's4',
        title: 'Ops alert bell',
        body: 'The header bell shows undismissed ops_alerts — overdue returns, payment issues, fleet holds. Open Notifications to dismiss after action.',
        adminHref: '/admin/notifications',
      },
      {
        id: 's5',
        title: 'Training vs SOPs',
        body: 'Use Training for tutorials and walkthroughs. Use Help & SOPs for formal procedures and checklists during live operations.',
        adminHref: '/admin/help',
      },
    ],
    relatedLinks: [
      { label: 'Command center', href: '/admin' },
      { label: 'Help & SOPs', href: '/admin/help' },
    ],
  },
  {
    slug: 'booking-operations',
    title: 'Booking operations',
    description: 'Manage the booking lifecycle from pending payment through completion.',
    track: 'operations',
    roles: 'all',
    keywords: ['booking', 'confirm', 'cancel', 'pending', 'active', 'hold'],
    estimatedMinutes: 25,
    objectives: [
      'Filter and open bookings by status',
      'Understand lifecycle gates before handover',
      'Use operations desk for holds and overrides (when permitted)',
    ],
    steps: [
      {
        id: 's1',
        title: 'Open the bookings pipeline',
        body: 'Admin → Bookings lists reservations. Filter by pending_payment, confirmed, active, completed, or cancelled. Click a row for full detail.',
        adminHref: '/admin/bookings',
      },
      {
        id: 's2',
        title: 'Review booking detail',
        body: 'Detail page shows customer, vehicle, dates, payment status, KYC link, inspection state, and internal notes. Read before any status change.',
      },
      {
        id: 's3',
        title: 'Payment gate',
        body: 'Do not hand over until payment policy is met — full, partial, or approved exception documented on the booking.',
        helpSlug: 'payment-collection',
      },
      {
        id: 's4',
        title: 'KYC gate',
        body: 'Customer profile must show KYC approved before pickup. Escalate to KYC queue if documents are pending.',
        adminHref: '/admin/kyc',
        helpSlug: 'kyc-verification',
      },
      {
        id: 's5',
        title: 'Ops holds',
        body: 'Operations → place hold when fraud, overlap, or missing docs. Release only after resolution. Force confirm is ops_admin only.',
        adminHref: '/admin/operations',
        helpSlug: 'booking-operations',
      },
      {
        id: 's6',
        title: 'Complete or cancel',
        body: 'After return and finance close-out, mark completed. Cancellations retain audit history — never delete booking rows.',
      },
    ],
    relatedLinks: [
      { label: 'Bookings', href: '/admin/bookings' },
      { label: 'Operations', href: '/admin/operations' },
    ],
  },
  {
    slug: 'kyc-verification',
    title: 'KYC verification',
    description: 'Work the identity review queue with consistent approve/reject standards.',
    track: 'operations',
    roles: ['kyc_reviewer', 'ops_admin', 'support_agent', 'fleet_manager', 'finance_manager'],
    keywords: ['kyc', 'aadhaar', 'license', 'approve', 'reject'],
    estimatedMinutes: 20,
    objectives: ['Open the KYC queue', 'Review all document types', 'Record clear rejection reasons'],
    steps: [
      { id: 's1', title: 'KYC queue', body: 'Admin → KYC shows customers with pending or reviewing documents. Prioritize same-day pickup flags.', adminHref: '/admin/kyc' },
      {
        id: 's2',
        title: 'Document review',
        body: 'Match names across IDs, check licence/passport expiry, verify selfie match. Open each document type before deciding.',
      },
      {
        id: 's3',
        title: 'Approve',
        body: 'Approve sets profile to approved and pins storage for retention. Customer can proceed to handover.',
        helpSlug: 'kyc-verification',
      },
      {
        id: 's4',
        title: 'Reject or resubmission',
        body: 'Reject with plain-language reason visible in customer dashboard. Resubmission required when only one document is unclear.',
      },
      {
        id: 's5',
        title: 'Escalation',
        body: 'Fraud suspicion → reject and flag via booking manual ops. Never approve incomplete sets under time pressure.',
        adminHref: '/admin/customers',
      },
    ],
    relatedLinks: [{ label: 'KYC queue', href: '/admin/kyc' }],
  },
  {
    slug: 'payment-management',
    title: 'Payment management',
    description: 'Record collections, partial payments, and reconcile the payments board.',
    track: 'operations',
    roles: ['finance_manager', 'ops_admin', 'support_agent'],
    keywords: ['payment', 'ledger', 'partial', 'razorpay', 'received'],
    estimatedMinutes: 22,
    objectives: ['Use the payments board', 'Mark receipts without duplicate entries', 'Understand partial payment rules'],
    steps: [
      { id: 's1', title: 'Payments board', body: 'Admin → Payments lists bookings with pending or partial payment_status.', adminHref: '/admin/payments' },
      {
        id: 's2',
        title: 'Verify amounts',
        body: 'On booking detail compare amount_due vs amount_paid with contract notes before recording.',
      },
      {
        id: 's3',
        title: 'Mark received',
        body: 'Payment panel → full or partial receipt with amount and notes. Creates payment_events ledger rows.',
        helpSlug: 'payment-collection',
      },
      {
        id: 's4',
        title: 'Gateway payments',
        body: 'When Razorpay is live, confirm webhook status before manual entry to avoid duplicates.',
      },
      {
        id: 's5',
        title: 'Disputes',
        body: 'Never delete ledger events. Finance adds corrective entries and documents in audit trail.',
      },
    ],
    relatedLinks: [{ label: 'Payments', href: '/admin/payments' }],
  },
  {
    slug: 'deposit-refund-handling',
    title: 'Deposit & refund handling',
    description: 'Hold deposits, apply deductions, and release refunds after return.',
    track: 'operations',
    roles: ['finance_manager', 'ops_admin'],
    keywords: ['deposit', 'refund', 'withhold', 'deduction'],
    estimatedMinutes: 24,
    objectives: ['Understand deposit statuses', 'Complete return inspection first', 'Process refunds with confirmation'],
    steps: [
      { id: 's1', title: 'Deposits board', body: 'Admin → Deposits (Financials) shows held amounts and refund queue.', adminHref: '/admin/financials' },
      {
        id: 's2',
        title: 'Deposit lifecycle',
        body: 'Statuses: pending → received → partially_refunded / withheld / released. Amount held lives on booking financial panel.',
        helpSlug: 'deposit-refund',
      },
      {
        id: 's3',
        title: 'After return',
        body: 'Finish return inspection and violations first. Net refund = deposit held minus approved deductions.',
      },
      {
        id: 's4',
        title: 'Withhold',
        body: 'Document each deduction line — damage, fuel, late return, fines. Customer communication should be itemized.',
      },
      {
        id: 's5',
        title: 'Mark refund processed',
        body: 'Only after bank/UPI confirmation. All changes are audit-logged.',
      },
    ],
    relatedLinks: [
      { label: 'Deposits', href: '/admin/financials' },
      { label: 'Violations', href: '/admin/violations' },
    ],
  },
  {
    slug: 'vehicle-handover-workflow',
    title: 'Vehicle handover workflow',
    description: 'Pickup inspection, signature, and activating the trip.',
    track: 'operations',
    roles: ['fleet_manager', 'ops_admin', 'support_agent'],
    keywords: ['handover', 'pickup', 'inspection', 'active'],
    estimatedMinutes: 22,
    objectives: ['Complete pickup inspection', 'Capture acknowledgement', 'Mark handed over'],
    steps: [
      {
        id: 's1',
        title: 'Pre-handover checks',
        body: 'Booking confirmed, KYC approved, payment policy met. Vehicle availability_status should be available.',
        adminHref: '/admin/fleet',
      },
      {
        id: 's2',
        title: 'Inspection workspace — pickup',
        body: 'Booking detail → Inspection: photos for exterior, interior, odometer, fuel. Save each slot before continuing.',
        helpSlug: 'vehicle-handover',
      },
      {
        id: 's3',
        title: 'Customer signature',
        body: 'Capture handover signature when device available — records customer_handover_signed_at.',
      },
      {
        id: 's4',
        title: 'Mark handed over',
        body: 'Operations workflow → Mark handed over. Sets handed_over_at and booking_status active.',
        adminHref: '/admin/operations',
      },
      {
        id: 's5',
        title: 'Customer walkthrough',
        body: 'Explain fuel policy, emergency contacts, and return time before customer drives away.',
      },
    ],
    relatedLinks: [{ label: 'Fleet', href: '/admin/fleet' }],
  },
  {
    slug: 'return-inspection-workflow',
    title: 'Return inspection workflow',
    description: 'Close-out inspection, damage notes, and marking returned.',
    track: 'operations',
    roles: ['fleet_manager', 'ops_admin', 'support_agent'],
    keywords: ['return', 'inspection', 'damage', 'completed'],
    estimatedMinutes: 22,
    objectives: ['Compare pickup vs return photos', 'Record penalties if needed', 'Mark returned then completed'],
    steps: [
      {
        id: 's1',
        title: 'Timing',
        body: 'Inspect at contract return time. Overdue returns appear on command center — contact customer before waiving fees.',
        adminHref: '/admin',
      },
      {
        id: 's2',
        title: 'Return inspection',
        body: 'Inspection workspace → Return phase: same angles as pickup. Record fuel, odometer, return_condition_notes.',
        helpSlug: 'vehicle-return-inspection',
      },
      {
        id: 's3',
        title: 'Mark returned',
        body: 'Operations → Mark returned (returned_at). Vehicle still active until trip completed.',
        adminHref: '/admin/operations',
      },
      {
        id: 's4',
        title: 'Penalties',
        body: 'Add violations or booking penalties before deposit release. Sync with financial panel.',
        adminHref: '/admin/violations',
      },
      {
        id: 's5',
        title: 'Complete trip',
        body: 'After finance clears deposit path, mark completed. Set vehicle to available or maintenance.',
        adminHref: '/admin/fleet',
      },
    ],
    relatedLinks: [{ label: 'Bookings', href: '/admin/bookings' }],
  },
  {
    slug: 'penalty-fine-management',
    title: 'Penalty & fine management',
    description: 'Record traffic violations, notify customers, and collect or deduct fines.',
    track: 'operations',
    roles: ['finance_manager', 'ops_admin', 'fleet_manager'],
    keywords: ['violation', 'challan', 'fine', 'penalty'],
    estimatedMinutes: 18,
    objectives: ['Create violations from booking', 'Attach challans', 'Sync with deposits'],
    steps: [
      {
        id: 's1',
        title: 'Violations list',
        body: 'Admin → Violations shows open fines across bookings. Filter by unpaid or deducted.',
        adminHref: '/admin/violations',
      },
      {
        id: 's2',
        title: 'Add violation',
        body: 'From booking detail → Violations: type, amount, date, upload challan PDF/image.',
        helpSlug: 'traffic-fine-management',
      },
      {
        id: 's3',
        title: 'Notify customer',
        body: 'Mark customer notified after WhatsApp/email. Note reference numbers in violation notes.',
      },
      {
        id: 's4',
        title: 'Collection',
        body: 'Paid separately → mark paid. Or deduct_from_deposit after finance approval.',
      },
      {
        id: 's5',
        title: 'Reconcile',
        body: 'Re-check booking financial panel after changes — penalties feed deposit calculations.',
        adminHref: '/admin/financials',
      },
    ],
    relatedLinks: [{ label: 'Violations', href: '/admin/violations' }],
  },
  {
    slug: 'staff-role-management',
    title: 'Staff role management',
    description: 'Assign roles, understand RBAC, and manage admin users safely.',
    track: 'operations',
    roles: ['ops_admin'],
    keywords: ['role', 'permission', 'rbac', 'users'],
    estimatedMinutes: 16,
    objectives: ['Know the five staff roles', 'Assign oxour_role via Users', 'Never share admin accounts'],
    steps: [
      {
        id: 's1',
        title: 'Role overview',
        body: 'support_agent (read-mostly), fleet_manager (fleet + bookings write), finance_manager (payments/deposits), kyc_reviewer (KYC only), ops_admin (full access).',
        helpSlug: 'staff-roles-permissions',
      },
      {
        id: 's2',
        title: 'Users page',
        body: 'Admin → Users lists staff. Assign role in app metadata — changes apply on next login.',
        adminHref: '/admin/users',
      },
      {
        id: 's3',
        title: 'Least privilege',
        body: 'Grant minimum role for the job. UI hiding is not security — server enforces every action.',
      },
      {
        id: 's4',
        title: 'Audit',
        body: 'Review staff actions in Audit log after role changes or incidents.',
        adminHref: '/admin/audit',
      },
    ],
    relatedLinks: [
      { label: 'Users', href: '/admin/users' },
      { label: 'Audit log', href: '/admin/audit' },
    ],
  },
  {
    slug: 'emergency-incident-handling',
    title: 'Emergency incident handling',
    description: 'Safety-first response for accidents, breakdowns, and critical events.',
    track: 'operations',
    roles: 'all',
    keywords: ['emergency', 'accident', 'safety', 'incident'],
    estimatedMinutes: 12,
    objectives: ['Prioritize safety over admin UI', 'Notify ops lead immediately', 'Document without admitting liability'],
    steps: [
      {
        id: 's1',
        title: 'Safety first',
        body: 'Ensure people are safe. Call emergency services (112) if injuries or road blockage. Admin actions come after.',
        tip: 'Life safety always precedes booking status updates.',
      },
      {
        id: 's2',
        title: 'Notify ops admin',
        body: 'Use your team on-call channel with booking ID, time, location, and vehicle.',
        helpSlug: 'emergency-incident',
      },
      {
        id: 's3',
        title: 'System flags',
        body: 'Fleet → accident_hold or maintenance. Booking → emergency cancel or hold via Operations.',
        adminHref: '/admin/operations',
      },
      {
        id: 's4',
        title: 'Evidence',
        body: 'Collect FIR, photos, third-party details. Upload to violations/inspection storage. Narrative in admin_internal_notes.',
      },
      {
        id: 's5',
        title: '24h review',
        body: 'Ops lead reviews audit log; insurance and customer comms per playbook.',
        adminHref: '/admin/audit',
      },
    ],
    relatedLinks: [{ label: 'Operations', href: '/admin/operations' }],
  },
  // Owner dashboard training
  {
    slug: 'owner-revenue-tracking',
    title: 'Revenue tracking',
    description: 'Read collected revenue, trends, and finance KPIs on the analytics dashboard.',
    track: 'owner',
    roles: ['ops_admin', 'finance_manager'],
    keywords: ['revenue', 'analytics', 'collections', 'owner'],
    estimatedMinutes: 14,
    objectives: ['Open analytics with date range', 'Interpret revenue cards', 'Export for reconciliation'],
    steps: [
      {
        id: 's1',
        title: 'Open analytics',
        body: 'Admin → Analytics shows revenue, bookings, fleet utilization for selected range (7d, 30d, custom).',
        adminHref: '/admin/analytics',
      },
      {
        id: 's2',
        title: 'Revenue metrics',
        body: 'Collected revenue reflects payment_events and booking payment_status — not hypothetical quotes.',
      },
      {
        id: 's3',
        title: 'Compare periods',
        body: 'Switch range to spot seasonality. Use command center for today; analytics for trends.',
        adminHref: '/admin',
      },
      {
        id: 's4',
        title: 'Export',
        body: 'Finance exports via Backup & DR for spreadsheet reconciliation with bank statements.',
        adminHref: '/admin/backup',
      },
    ],
    relatedLinks: [{ label: 'Analytics', href: '/admin/analytics' }],
  },
  {
    slug: 'owner-pending-dues',
    title: 'Pending dues',
    description: 'Monitor open balances and collection risk across the fleet.',
    track: 'owner',
    roles: ['ops_admin', 'finance_manager'],
    keywords: ['dues', 'pending', 'collections', 'arrears'],
    estimatedMinutes: 12,
    objectives: ['Read pending collection totals', 'Drill into payments board', 'Prioritize high-value arrears'],
    steps: [
      {
        id: 's1',
        title: 'Command center finance strip',
        body: 'Home dashboard shows pending payment counts and rupee exposure — refresh at shift start.',
        adminHref: '/admin',
      },
      {
        id: 's2',
        title: 'Payments board',
        body: 'Payments page filters pending and partial bookings. Sort by pickup date for same-day risk.',
        adminHref: '/admin/payments',
      },
      {
        id: 's3',
        title: 'Pending dues export',
        body: 'Backup & DR → export pending-dues for weekly owner review meetings.',
        adminHref: '/admin/backup',
      },
      {
        id: 's4',
        title: 'Escalation',
        body: 'Ops hold or finance write-off requires documented notes — never silent waivers.',
      },
    ],
    relatedLinks: [{ label: 'Payments', href: '/admin/payments' }],
  },
  {
    slug: 'owner-fleet-analytics',
    title: 'Fleet analytics',
    description: 'Utilization, availability, and maintenance signals for the vehicle catalog.',
    track: 'owner',
    roles: ['ops_admin', 'fleet_manager', 'finance_manager'],
    keywords: ['fleet', 'utilization', 'availability', 'maintenance'],
    estimatedMinutes: 14,
    objectives: ['Read fleet utilization charts', 'Identify maintenance holds', 'Balance catalog vs demand'],
    steps: [
      {
        id: 's1',
        title: 'Analytics fleet section',
        body: 'Analytics dashboard includes active trips, idle vehicles, and category mix.',
        adminHref: '/admin/analytics',
      },
      {
        id: 's2',
        title: 'Fleet catalog',
        body: 'Fleet page shows availability_status per vehicle: available, on_trip, maintenance, accident_hold.',
        adminHref: '/admin/fleet',
      },
      {
        id: 's3',
        title: 'Command center fleet cards',
        body: 'Dashboard highlights maintenance and accident_hold counts — investigate before marketing pushes.',
        adminHref: '/admin',
      },
      {
        id: 's4',
        title: 'Archived vehicles',
        body: 'Archived units are excluded from availability but remain in reports. Restore via Backup & DR if needed.',
        adminHref: '/admin/backup',
      },
    ],
    relatedLinks: [{ label: 'Fleet', href: '/admin/fleet' }],
  },
  {
    slug: 'owner-operational-monitoring',
    title: 'Operational monitoring',
    description: 'Alerts, audit, launch readiness, and day-to-day health for owners.',
    track: 'owner',
    roles: ['ops_admin', 'finance_manager'],
    keywords: ['monitoring', 'alerts', 'audit', 'launch', 'health'],
    estimatedMinutes: 16,
    objectives: ['Triage ops alerts daily', 'Use audit for accountability', 'Review launch checklist before go-live'],
    steps: [
      {
        id: 's1',
        title: 'Ops notifications',
        body: 'Clear or action undismissed alerts each morning. Backlog >10 items needs ops lead triage.',
        adminHref: '/admin/notifications',
      },
      {
        id: 's2',
        title: 'Audit log',
        body: 'Filter audit by actor, entity, or action for dispute resolution and training feedback.',
        adminHref: '/admin/audit',
      },
      {
        id: 's3',
        title: 'Launch control center',
        body: 'Pre-go-live: review readiness %, environment URLs, and failed backup alerts.',
        adminHref: '/admin/launch',
      },
      {
        id: 's4',
        title: 'Backup health',
        body: 'Weekly check of backup indicators and export test on staging.',
        adminHref: '/admin/backup',
      },
    ],
    relatedLinks: [
      { label: 'Notifications', href: '/admin/notifications' },
      { label: 'Launch', href: '/admin/launch' },
    ],
  },
] as const
